#!/bin/bash

for queue in 2 3 4 5 6 7 8 10 12 16 20; do
    echo -n "4 threads, buffer=8192, queue=$queue: "
    java -jar tetra-string.jar -s 7 -e 7 -t 4 -q $queue -b 8192 | grep -o '..:..:..:...'
    /bin/rm -rf Results/L7
done
