#!/bin/bash

/bin/rm tetranucleo.tar.gz 2>/dev/null
mkdir tetranucleo
cp target/tetra-1.0-SNAPSHOT-jar-with-dependencies.jar tetranucleo/tetranucleo.jar
cp -r data tetranucleo
tar zcvf tetranucleo.tar.gz tetranucleo
/bin/rm -rf tetranucleo
